# Generated by Django 4.1.2 on 2022-11-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_actor_movie_acrors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='acrors',
            new_name='actors',
        ),
    ]
